from django.db import models

# Create your models here.

class Organization(models.Model):
    ein = models.CharField(max_length=9)
    name = models.CharField(max_length=1023)
    city = models.CharField(max_length=1023)
    state = models.CharField(max_length=2)
    country = models.CharField(max_length=63)
    indicator = models.CharField(max_length=15)


    careofname = models.CharField(max_length=255, blank=True, null=True)
    revenue_amount = models.IntegerField(blank=True, null=True)
    activity_codes = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    zipcode = models.CharField(max_length=255, blank=True, null=True)
    exemption_number = models.CharField(max_length=255, blank=True, null=True)
    subsection_code = models.CharField(max_length=255, blank=True, null=True)
    affiliation_code = models.CharField(max_length=255, blank=True, null=True)
    classification_codes = models.CharField(max_length=255, blank=True, null=True)
    ruling_date = models.CharField(max_length=255, blank=True, null=True)
    deductibility_code = models.CharField(max_length=255, blank=True, null=True)
    foundation_code = models.CharField(max_length=255, blank=True, null=True)
    organization_code = models.CharField(max_length=255, blank=True, null=True)
    exempt_organization_status_code = models.CharField(max_length=255, blank=True, null=True)
    tax_period = models.CharField(max_length=255, blank=True, null=True)
    asset_code = models.CharField(max_length=255, blank=True, null=True)
    income_code = models.CharField(max_length=255, blank=True, null=True)
    filing_requirement_code = models.CharField(max_length=255, blank=True, null=True)
    pf_filing_requirement_code = models.CharField(max_length=255, blank=True, null=True)
    accounting_period = models.CharField(max_length=255, blank=True, null=True)
    asset_amount = models.IntegerField(blank=True, null=True)
    income_amount = models.IntegerField(blank=True, null=True)
    sort_name = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.CharField(max_length=255, blank=True, null=True)
    updated_at = models.CharField(max_length=255, blank=True, null=True)
    data_source = models.CharField(max_length=255, blank=True, null=True)
    have_extracts = models.CharField(max_length=255, blank=True, null=True)
    have_pdfs = models.CharField(max_length=255, blank=True, null=True)
    latest_object_id = models.CharField(max_length=255, blank=True, null=True)
    ntee_code = models.CharField(max_length=255, blank=True, null=True)

# class FiscalYear(models.Model):
#     year = models.CharField(max_length=4)
#     formtype = models.CharField(max_length=2)
#     pdf_url = models.CharField(max_length=511)
#     last_updated = models.CharField(max_length=511)

#     revenue = models.IntegerField()
#     total_functional_expenses = models.IntegerField()
#     total_assets_end = models.IntegerField()
#     total_liabilities_end = models.IntegerField()
    
#     tax_period = models.CharField(max_length=15)
#     subseccd = models.CharField(max_length=15)
#     unrelbusinccd = models.CharField(max_length=15)
#     initiation_fees = models.CharField(max_length=15)
#     grsrcptspublicuse = models.CharField(max_length=15)
#     grsincmembers = models.CharField(max_length=15)
#     grsincother = models.CharField(max_length=15)

#     totcntrbgfts = models.IntegerField()
#     totprgmrevnue = models.IntegerField()
#     invstmntinc = models.IntegerField()
#     txexmptbndsproceeds = models.IntegerField()
#     royaltsinc = models.IntegerField()
#     grsrntsreal = models.IntegerField()
#     grsrntsprsnl = models.IntegerField()
#     rntlexpnsreal = models.IntegerField()
#     rntlexpnsprsnl = models.IntegerField()
#     rntlincreal = models.IntegerField()
#     rntlincprsnl = models.IntegerField()
#     netrntlinc = models.IntegerField()
#     grsalesecur = models.IntegerField()
#     grsalesothr = models.IntegerField()
#     cstbasisecur = models.IntegerField()
#     cstbasisothr = models.IntegerField()
#     gnlsecur = models.IntegerField()
#     gnlsothr = models.IntegerField()
#     netgnls = models.IntegerField()
#     grsincfndrsng = models.IntegerField()
#     lessdirfndrsng = models.IntegerField()
#     netincfndrsng = models.IntegerField()
#     grsincgaming = models.IntegerField()
#     lessdirgaming = models.IntegerField()
#     netincgaming = models.IntegerField()
#     grsalesinvent = models.IntegerField()
#     lesscstofgoods = models.IntegerField()
#     netincsales = models.IntegerField()
#     miscrevtot11e = models.IntegerField()
#     compnsatncurrofcr = models.IntegerField()
#     othrsalwages = models.IntegerField()
#     payrolltx = models.IntegerField()
#     profndraising = models.IntegerField()
#     txexmptbndsend = models.IntegerField()
#     secrdmrtgsend = models.IntegerField()
#     unsecurednotesend = models.IntegerField()
#     retainedearnend = models.IntegerField()
#     totnetassetend = models.IntegerField()

#     nonpfrea = models.CharField(max_length=15)

#     gftgrntsrcvd170 = models.IntegerField()
#     txrevnuelevied170 = models.IntegerField()
#     srvcsval170 = models.IntegerField()
#     grsinc170 = models.IntegerField()
#     grsrcptsrelated170 = models.IntegerField()
#     totgftgrntrcvd170 = models.IntegerField()
#     totgftgrntrcvd509 = models.IntegerField()
#     totgftgrntrcvd509 = models.IntegerField()
#     grsrcptsadmissn509 = models.IntegerField()
#     txrevnuelevied509 = models.IntegerField()
#     srvcsval509 = models.IntegerField()
#     subtotsuppinc509 = models.IntegerField()
#     totsupp509 = models.IntegerField()
