# Generated by Django 5.1 on 2024-09-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0008_remove_organization_projects_delete_project'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(to='analyst.organization'),
        ),
    ]
