# Generated by Django 5.1 on 2024-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=1023)),
                ('city', models.CharField(max_length=1023)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=63)),
                ('indicator', models.CharField(max_length=15)),
            ],
        ),
    ]
