# Generated by Django 5.1 on 2024-09-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0003_city_state_organization_hq_city_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
