# Generated by Django 5.1 on 2024-09-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0004_organization_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organizations', models.ManyToManyField(to='analyst.organization')),
            ],
        ),
    ]
