# Generated by Django 5.1 on 2024-09-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organizations',
        ),
    ]
