# Generated by Django 5.1 on 2024-09-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0006_remove_project_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='projects',
            field=models.ManyToManyField(to='analyst.project'),
        ),
    ]
