# Generated by Django 5.1 on 2024-09-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0007_organization_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
